/**
 * LANGUAGE STATION — Dialog Engine
 *
 * Runs dialog trees. Nodes can be:
 *   - authored:  written by a human, static
 *   - gm:        generated by the AI GM, injected at load or runtime
 *   - station:   special class — the Station itself speaking (Act 2+)
 *
 * The player should not be able to tell authored from gm by looking at the UI.
 * The seam becomes legible only through content, not presentation.
 */

import { writable, get } from 'svelte/store';
import { activeDialog, setFlag, addToInventory } from './state.js';

// ── Dialog history ────────────────────────────────────────────────────────
// Full transcript of the current conversation, for GM context
export const dialogHistory = writable([]);

/**
 * Start a dialog with an NPC or object.
 * node: DialogNode — the entry point
 */
export function startDialog(node) {
  dialogHistory.set([]);
  activeDialog.set(node);
}

/**
 * Choose an option and advance the dialog.
 * option: DialogOption
 */
export function chooseOption(option) {
  const current = get(activeDialog);
  if (!current) return;

  // Record to history
  dialogHistory.update(h => [
    ...h,
    { speaker: 'player', text: option.text, source: option.source ?? 'authored' }
  ]);

  // Apply any side effects
  if (option.setFlag) setFlag(option.setFlag);
  if (option.giveItem) addToInventory(option.giveItem);

  // Advance
  if (option.next) {
    activeDialog.set(option.next);
    dialogHistory.update(h => [
      ...h,
      {
        speaker: option.next.speaker ?? 'npc',
        text: option.next.text,
        source: option.next.source ?? 'authored',
      }
    ]);
  } else {
    // End of dialog
    activeDialog.set(null);
  }
}

/**
 * Close dialog (player walks away, etc.)
 */
export function closeDialog() {
  activeDialog.set(null);
}

// ── Type definitions (JSDoc) ──────────────────────────────────────────────

/**
 * @typedef {Object} DialogNode
 * @property {string} id
 * @property {string} speaker      - npc id, 'station', 'player', 'narrator'
 * @property {string} text         - what is said/shown
 * @property {'authored'|'gm'|'station'} source   - origin (NOT shown to player)
 * @property {DialogOption[]} options
 */

/**
 * @typedef {Object} DialogOption
 * @property {string} text
 * @property {'authored'|'gm'|'station'} source   - origin (NOT shown to player)
 * @property {string} [setFlag]    - flag to set when chosen
 * @property {string} [giveItem]   - item to add to inventory
 * @property {DialogNode} [next]   - next node (null = end dialog)
 */
